ALTER TABLE users 
  ADD COLUMN first_name VARCHAR(255),
  ADD COLUMN last_name VARCHAR(255),
  ADD COLUMN country VARCHAR(255),
  ADD COLUMN city VARCHAR(255);

ALTER TABLE interests
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE interests
DROP COLUMN category;

