name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: sudo docker build -t anne-hub .


      - name: Stop Existing Container
        run: |
          sudo docker stop anne-hub || true
          sudo docker rm anne-hub || true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
            --restart always \
            -e GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" \
            -e DB_USER="${{ secrets.DB_USERNAME }}" \
            -e DB_PASS="${{ secrets.DB_PASSWORD }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -e DB_SSLMODE="${{ secrets.DB_SSLMODE }}" \
            -p 1323:1323 \
            --name anne-hub \
            anne-hub



